import { Products } from "@/utils/types";

export const productSet1: Products[] = [
  {
    name: "MO231 - Pomeranian White",
    genre: "Male",
    age: 2,
    ageUnit: "months",
    price: 6900000,
    image: "/assets/products/image1.png",
  },
  {
    name: "MO502 - Poodle Tiny Yellow",
    genre: "Female",
    age: 2,
    ageUnit: "months",
    price: 3900000,
    image: "/assets/products/image2.png",
  },
  {
    name: "MO102 - Poodle Tiny Sepia",
    genre: "Male",
    age: 2,
    ageUnit: "months",
    price: 4000000,
    image: "/assets/products/image3.png",
  },
  {
    name: "MO512 - Alaskan Malamute Grey",
    genre: "Female",
    age: 3,
    ageUnit: "months",
    price: 8900000,
    image: "/assets/products/image4.png",
  },
  {
    name: "MO231 - Pembroke Corgi Cream",
    genre: "Male",
    age: 3,
    ageUnit: "months",
    price: 7900000,
    image: "/assets/products/image5.png",
  },
  {
    name: "MO502 - Pembroke Corgi Tricolor",
    genre: "Female",
    age: 2,
    ageUnit: "months",
    price: 6900000,
    image: "/assets/products/image6.png",
  },
  {
    name: "MO102 -  Pomeranian Grey",
    genre: "Female",
    age: 2,
    ageUnit: "months",
    price: 6500000,
    image: "/assets/products/image7.png",
  },
  {
    name: "MO512 - Poodle Tiny Dairy Cow",
    genre: "Male",
    age: 3,
    ageUnit: "months",
    price: 5000000,
    image: "/assets/products/image8.png",
  },
];
