import { Products } from "@/utils/types";

export const productSet1: Products[] = [
  {
    name: "MO231 - Pomeranian White",
    genre: "Male",
    age: 2,
    ageUnit: "months",
    price: 6900000,
    image: "/assets/products/image1.png",
  },
  {
    name: "MO502 - Poodle Tiny Yellow",
    genre: "Female",
    age: 2,
    ageUnit: "months",
    price: 3900000,
    image: "/assets/products/image2.png",
  },
  {
    name: "MO102 - Poodle Tiny Sepia",
    genre: "Male",
    age: 2,
    ageUnit: "months",
    price: 4000000,
    image: "/assets/products/image3.png",
  },
  {
    name: "MO512 - Alaskan Malamute Grey",
    genre: "Female",
    age: 3,
    ageUnit: "months",
    price: 8900000,
    image: "/assets/products/image4.png",
  },
  {
    name: "MO231 - Pembroke Corgi Cream",
    genre: "Male",
    age: 3,
    ageUnit: "months",
    price: 7900000,
    image: "/assets/products/image5.png",
  },
  {
    name: "MO502 - Pembroke Corgi Tricolor",
    genre: "Female",
    age: 2,
    ageUnit: "months",
    price: 6900000,
    image: "/assets/products/image6.png",
  },
  {
    name: "MO102 -  Pomeranian Grey",
    genre: "Female",
    age: 2,
    ageUnit: "months",
    price: 6500000,
    image: "/assets/products/image7.png",
  },
  {
    name: "MO512 - Poodle Tiny Dairy Cow",
    genre: "Male",
    age: 3,
    ageUnit: "months",
    price: 5000000,
    image: "/assets/products/image8.png",
  },
];

export const productSet2: Products[] = [
  {
    name: "Reflex Plus Adult Cat Food Salmon",
    type: "Dog Food",
    weight: 385,
    price: 140000,
    image: "/assets/products/image9.png",
    free: "Toy & Free Shaker",
  },
  {
    name: "Reflex Plus Adult Cat Food Salmon",
    type: "Cat Food",
    weight: 1500,
    price: 165000,
    image: "/assets/products/image10.png",
    free: "Toy & Free Shaker",
  },
  {
    name: "Cat scratching ball toy kitten sisal rope ball",
    type: "Toy",
    weight: null,
    price: 1100000,
    image: "/assets/products/image11.png",
    free: "Cat Food",
  },
  {
    name: "Cute Pet Cat Warm Nest",
    type: "Toy",
    weight: null,
    price: 410000,
    image: "/assets/products/image12.png",
    free: "Cat Food",
  },
  {
    name: "NaturVet Dogs - Omega-Gold Plus Salmon Oil",
    type: "Dog Food",
    weight: 385,
    price: 350000,
    image: "/assets/products/image13.png",
    free: "Toy & Free Shaker",
  },
  {
    name: "Costumes Fashion Pet Clother Cowboy Rider",
    type: "Costume",
    weight: 1500,
    price: 500000,
    image: "/assets/products/image14.png",
    free: "Toy & Free Shaker",
  },
  {
    name: "Costumes Chicken Drumsti ck Headband",
    type: "Costume",
    weight: null,
    price: 400000,
    image: "/assets/products/image15.png",
    free: "Cat Food",
  },
  {
    name: "Plush Pet Toy",
    type: "Toy",
    weight: null,
    price: 250000,
    image: "/assets/products/image16.png",
    free: "Food & Shaker",
  },
];
